### ISSUE TITLE
Labeling - ITU Racing 

### ISSUE THREAD

**Issue by kharitonov-ivan** [ddavid/fsoco#54]
Hey, @ddavid , @Isydmr ! The wrong labeling on  [ITU racings dataset](https://github.com/ddavid/fsoco/commit/c82dcbea2a34e1f036adb4fe2612657bbab38f99) caught my attention.
Here are some examples.

[cju0a8eeb18k80835ygl5yk09.txt](https://github.com/ddavid/fsoco/blob/288d11a0e1bcad4809d75834cf8b99cc425a1732/labels/ituracing/itu_2019/cju0a8eeb18k80835ygl5yk09.txt#L1)
![image](https://user-images.githubusercontent.com/25615790/74089335-31006e00-4ab1-11ea-8054-102f56979552.png)

[cjtnj9pptrmjk0835v7gul4gp.txt](https://github.com/ddavid/fsoco/blob/288d11a0e1bcad4809d75834cf8b99cc425a1732/labels/ituracing/itu_2019/cjtnj9pptrmjk0835v7gul4gp.txt#L1)
![image](https://user-images.githubusercontent.com/25615790/74089394-e2070880-4ab1-11ea-887c-c319c334e59b.png)

[cjtyu71zs92zj0801lkgtnkaa.txt](https://github.com/ddavid/fsoco/blob/288d11a0e1bcad4809d75834cf8b99cc425a1732/labels/ituracing/itu_2019/cjtyu71zs92zj0801lkgtnkaa.txt#L1)
![image](https://user-images.githubusercontent.com/25615790/74089415-0f53b680-4ab2-11ea-895e-606df1c1c7c8.png)

I found a lot of this, could you please check this dataset?

Best regards, 
Ivan

**Comment by ddavid** [comment]
Hi Ivan,
will have a look at it together with some further changes to the GET dataset tomorrow.
Thank you for pointing this out.

**Comment by ddavid** [comment]
Will have to postpone to tomorrow unfortunately.

**Comment by ddavid** [comment]
Can confirm your findings, a few images are lacking labels and a lot of them have the wrong class - always one class for the whole image.
Tests were still being done by sampling back when the PR was done, that's probably why it went unnoticed.
Thank you for pointing this out here.
I'll prepend a prefix to the directory name and labels so others notice it. The data set should definitely not be used until the labeling is fixed.
@Isydmr Could you please look into the mislabeled files?

**Comment by Isydmr** [comment]
I'll contact my team about this, will inform you when we fix labels.
Thank you for your understanding.

**Comment by ddavid** [comment]
PR opened with revised labels #64

**Comment by Isydmr** [comment]
Thank you for reporting our mistakes guys, we improved our labeling a lot. 
It is very nice to see the continuous growth of this dataset.
This issue can be **closed**. #64 merged by @ddavid.
