### ISSUE TITLE
access to the training dataset

### ISSUE THREAD

**Issue by fused-byte** [ddavid/fsoco#66]
Hi, I would like access to the annotated training dataset. I am from the KTH formula student team and we have previously contributed in the annotation as well.

**Comment by ddavid** [comment]
Hi fused-byte, the datasets have already been shared with the new account you shared in our e-mail exchange. Please check your access with the kthfsdv@gmail.com account and let me know if anything isn't working as expected.

![2020-03-16_Selection-01](https://user-images.githubusercontent.com/18621443/76806314-4f106b00-67e1-11ea-94b1-261533772f8f.png)

**Comment by fused-byte** [comment]
Hi David, Yes we have got the access.
Thanks
